spring.application.name=staffManagementServer
spring.datasource.url=jdbc:mysql://localhost:3306/staffManagementServer
spring.datasource.username=root
spring.datasource.password=2003
security.jwt.secret-key=soyUnaKey
server.port=9000
spring.jackson.time-zone=America/Argentina/Buenos_Aires
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true